### ISSUE TITLE
Refactor code

### ISSUE THREAD

**Issue by tejuamirthi** [tejuamirthi/CustomDropDown#12]
Seperate the views into different files in the framework
Code clean up and add comments at places
Update relevant documentation

**Comment by jacquealvesb** [comment]
Hi, Tejeshwar, do you know if there's someone still working on this? I would like to try ☺️

**Comment by tejuamirthi** [comment]
Hi @jacquealvesb, thank you for the interest. 
Yes, this issue is open. Right now, no one is working. The code was updated after the above pr and needs a good amount of refactoring and clean up. Would really appreciate any help

Would you like this to be assigned to you?

**Comment by jacquealvesb** [comment]
Yeah, sure!

**Comment by tejuamirthi** [comment]
If you need anything, I'm always open for a discussion.
