### ISSUE TITLE
[BUG] adjust the label height according to length of the text

### ISSUE THREAD

**Issue by tejuamirthi** [tejuamirthi/CustomDropDown#14]
**Describe the bug**
Right now, when the text of any row is more than one line, the text is truncated at the end. Also if single line text is there, bottom part of the text is cut.

**Expected behavior**
Label height should be the height of the text in any number of lines it may be plus the padding from top and bottom

**Smartphone (please complete the following information):**
 - Device: iPhone 11 pro max
 - OS: 13.3
 - Xcode: 11.3.1

**Additional context**
Work on the CustomDropDown.swift view file
https://github.com/tejuamirthi/CustomDropDown/blob/abec4aa81de3d1362c254c326f53a053f404edc2/CustomDropDown/View/CustomDropDown.swift#L75

**Comment by devanshimodha** [comment]
Resolve this

**Comment by tejuamirthi** [comment]
> Resolve this

I'll resolve this soon if no one picks it up. Please feel free to contribute!

**Comment by devanshimodha** [comment]
Sorry! I meant Resolved this; Please Check the PR

**Comment by tejuamirthi** [comment]
Assigned to you! @devanshimodha
