### ISSUE TITLE
[FR] Update the example project properly with dropdown styles

### ISSUE THREAD

**Issue by tejuamirthi** [tejuamirthi/CustomDropDown#16]
**Is your feature request related to a problem? Please describe.**
Right now, example project is not the whole picture. Need to display dropdown styles clearly

**Describe the solution you'd like**
Use the CustomDropDown framework as it is used earlier and display the example projects for both the styles. Label and ImageLabel which are being supported currently. Right now, example project shows only one example.

**Additional context**
[Refer here](https://github.com/tejuamirthi/CustomDropDown/blob/254c209aa8c7234c4d2cdac664942beccefb3793/Example/ViewController.swift#L19) for more info. You'll need to add another view and make it use the other DropDown style.

Feel free to reach out for a discussion!

**Comment by FranklinSamboni** [comment]
@tejuamirthi, is this available, isn't it?
