### ISSUE TITLE
[BUG] DropDown toggle

### ISSUE THREAD

**Issue by tejuamirthi** [tejuamirthi/CustomDropDown#17]
**Describe the bug**
Right now, when we click on any part of the screen and if the dropdown is expanded already, it doesn't close.

**To Reproduce**
Add a dropdown and try expanding and closing by tapping on different areas on screen

**Expected behavior**
DropDown should collapse as soon as the user hits anywhere on the screen(If user hits on the dropdown view itself, it is handled)

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro Max simulator
 - OS: 13.3
 - Xcode: 11.3.1

**Comment by FranklinSamboni** [comment]
Hello there, I am working in this. Can you assign me this task ?

**Comment by tejuamirthi** [comment]
Thank you for the interest @FranklinSamboni 
Assigned

Contact me if you need anything else. Let me know the progress as well if you could, whenever necessary. Thanks!

**Comment by FranklinSamboni** [comment]
Done :D, if you have some feedback let me know. I also see a refactor code task running so I tried to change few things as possible to don't generate conflicts.

**Comment by devanshimodha** [comment]
Is this solved or not as the tag is available?

**Comment by tejuamirthi** [comment]
Hey @devanshimodha 
There’s a recent update in the ongoing pr, so have to review that before I can conclude the functionality. Please take a look at other issues and I’ll be a few new issues soon as well! Thank you for the interest

**Comment by tejuamirthi** [comment]
Mean time you can try #16 @devanshimodha 
It’s a simple but necessary one! Let me know if you need anything
