### ISSUE TITLE
[FR] Enhancement - Add corner radius and shadow to the dropdown tableview

### ISSUE THREAD

**Issue by tejuamirthi** [tejuamirthi/CustomDropDown#20]
**Is your feature request related to a problem? Please describe.**
DropDown tableview appearance need to be updated

**Describe the solution you'd like**
Add corner radius and shadow for the dropdown tableview and add new options in the config for users to customise

**Comment by Pancreax** [comment]
Hi! I would like to work on this issue! 🙂

**Comment by tejuamirthi** [comment]
Hi @Pancreax 
Thank you for your interest. Assigned the issue to you. Let me know if you need any help!
Create a pr and request review once done.
