### ISSUE TITLE
[BUG] Terminating app due to uncaught exception 'NSGenericException'

### ISSUE THREAD

**Issue by FranklinSamboni** [tejuamirthi/CustomDropDown#27]
**Describe the bug**
The framework is generate an app crash when the superview of the custom drop down view is nil. 

**To Reproduce**
- Create an project with two ViewControllers embebed in a NavigationViewController
- In the first one just put a segue to the SecondViewController. 
- In the SecondViewController implement the CustomDropDown framework 
- Run and navigate to SecondViewController. 
- Tap on Back button of Navigation Item, then app crash. 

**Expected behavior**
- An app should be navigated back successfully and the framework shouldn't generate this crash.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Simulator iPhone 11 Pro Max
 - OS: iOS 14
 - Xcode: 12.0.1

**Additional context**
Copy of error:
Terminating app due to uncaught exception 'NSGenericException', reason: 'Unable to activate constraint with anchors <NSLayoutYAxisAnchor:0x6000003b3b80 "_TtGC14CustomDropDown14CustomDropDownSS_:0x7fb7a340f320.top"> and <NSLayoutYAxisAnchor:0x60000038c000 "_TtGC14CustomDropDown18CustomDropDownViewSS_:0x7fb7a340e1e0.bottom"> because they have no common ancestor.  Does the constraint or its anchors reference items in different view hierarchies?  That's illegal.'

**Comment by tejuamirthi** [comment]
Would you like to work on this issue? @FranklinSamboni

**Comment by FranklinSamboni** [comment]
Yes, I would like.

**Comment by tejuamirthi** [comment]
I completed this one. Just now. Was going to push.

**Comment by tejuamirthi** [comment]
Will update the repo tomorrow. Would be great if you could do it by morning tomorrow. Thanks @FranklinSamboni 
It's just a couple of lines of code

**Comment by FranklinSamboni** [comment]
Of course, but here in Colombia is morning hehe, so I will fixed soon.

**Comment by tejuamirthi** [comment]
Please share a screen recording of the working app after the fix. It'd really help. Thanks!

**Comment by FranklinSamboni** [comment]
[Example App](https://drive.google.com/file/d/1yGYc8DHio2jp2yxbhf-rnbKrXe6rik0y/view?usp=sharing)
