### ISSUE TITLE
[BUG] Text overlap

### ISSUE THREAD

**Issue by devanshimodha** [tejuamirthi/CustomDropDown#28]
**Describe the bug**
The text in the dropdown view overlaps if we add more items in dropdown

**To Reproduce**
Add multiple items in the array
Scroll down the drop-down view

**Expected behavior**
The text should not overlap

**Screenshots**
![Simulator Screen Shot - iPhone SE (2nd generation) - 2020-10-27 at 10 19 50](https://user-images.githubusercontent.com/32483283/97258303-2dc73100-183e-11eb-9359-77c8f90f8776.png)

**Smartphone (please complete the following information):**
 - Device: iPhone SE (2nd Generation)
 - OS: iOS 13.5.0
 - Xcode: 12.0

**Comment by tejuamirthi** [comment]
Would you like to work on this? @devanshimodha ?
